unbind-key -a

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# execute commands
bind : command-prompt
bind f command-prompt -p (find-window) "find-window '%%'"
bind , command-prompt -p (rename-window) "rename-window '%%'"
bind $ command-prompt -p (rename-session) "rename-session '%%'"
bind x confirm-before -p "kill-pane #P? (y/n)" kill-pane

#split panes using | and -
bind | split-window -h
bind - split-window -v
bind ! break-pane

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resizing
bind-key -r C-Up resize-pane -U
bind-key -r C-Down resize-pane -D
bind-key -r C-Left resize-pane -L
bind-key -r C-Right resize-pane -R

# layouts
bind Space next-layout

# session management
bind ( switch-client -p
bind ) switch-client -n
bind d detach-client
bind D choose-client


# window navigation
bind 0 select-window -t :0
bind 1 select-window -t :1
bind 2 select-window -t :2
bind 3 select-window -t :3
bind 4 select-window -t :4
bind 5 select-window -t :5
bind 6 select-window -t :6
bind 7 select-window -t :7
bind 8 select-window -t :8
bind 9 select-window -t :9
bind n next-window
bind p previous-window
bind w choose-window
bind c new-window

# naming


bind r source-file ~/.tmux.conf

set-window-option -g mode-keys vi
set -g status-keys vi

set -g mouse on

set-option -g allow-rename off

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

setw -g clock-mode-colour yellow
setw -g mode-style 'fg=black bg=red bold'
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'


